apiVersion: v1
kind: Secret
metadata:
  name: config-data
data:
  user: c3lzb3A=
  password: UzR2aWxsMw==
stringData:
  haiku: |2
    Eclipse of the moon
    The sun shining brightly
    Smoke filling the room
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod 
  labels:
    app: testpod
    tier: quicktest
    colour: turquoise
spec:
  shareProcessNamespace: true
  volumes:
  - name: scratchpad
    emptyDir: {}
  - name: config-data
    secret:
      secretName: config-data
  containers:
  - name: alpine
    image: alpine
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    args: []
    env:
    - name: user
      valueFrom:
        secretKeyRef:
          name: config-data
          key: user
    - name: password
      valueFrom:
        secretKeyRef:
          name: config-data
          key: password
    volumeMounts:
    - name: scratchpad
      mountPath: /usr/share/nginx/html
    - name: config-data
      mountPath: /srv/haiku
      subPath: haiku
    resources:
      requests: {memory: 100Mi, cpu: 0.1}
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts: 
    - name: scratchpad
      mountPath: /usr/share/nginx/html
    resources:
      requests: {memory: 200Mi, cpu: 0.1}
